apiVersion: v1
kind: Service
metadata:
  name: gestion-classe
  namespace: preprod
spec:
  selector:
    app: gestion-classe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: NodePort
  